<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Classrooms</name>
   <tag></tag>
   <elementGuidId>a86669ab-2036-415b-b60f-793f21decbee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='TEXT'])[25]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64e03248-a23d-4de9-b1e6-d8c0cc9e87af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>59680bdf-ff6e-47c4-b583-a4a2cf63e828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Classrooms</value>
      <webElementGuid>f5b257b5-4334-4ed4-9ae8-f5affcf39142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;gwt-PopupPanel&quot;]/div[@class=&quot;popupContent&quot;]/table[1]/tbody[1]/tr[2]/td[1]/button[@class=&quot;z-MenuItem-Action&quot;]/span[@id=&quot;TEXT&quot;]</value>
      <webElementGuid>97fb0433-aad4-4ce4-a30b-583c2c7f8c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='TEXT'])[25]</value>
      <webElementGuid>f583e051-be6b-4ec2-972f-523c303c6594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School Details'])[1]/following::span[1]</value>
      <webElementGuid>9122b76e-ccf9-4e5a-868e-2b00ada70f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading data'])[1]/following::span[2]</value>
      <webElementGuid>8f4ece6e-1732-4321-8ccd-7787703f3dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Classrooms']/parent::*</value>
      <webElementGuid>bc1d4306-90c0-4cba-a5ec-da4223269986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/button/span</value>
      <webElementGuid>60011b55-39ac-427a-a136-96a6d9da07b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'TEXT' and (text() = 'Classrooms' or . = 'Classrooms')]</value>
      <webElementGuid>069f608f-7dda-4298-9be2-54546f7267fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
