<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_house_z-DisclosureIcon-Image</name>
   <tag></tag>
   <elementGuidId>305bccfc-7802-4033-bcd3-a29147f3ba11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.z-DisclosureIcon-Image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4650a1d4-3e76-4f8e-a5e2-b1c78bd20116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>system/icons/disclosure_right.png</value>
      <webElementGuid>59457481-2f5e-4df9-9e53-0eb1236e8996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-DisclosureIcon-Image</value>
      <webElementGuid>626cb5a4-ab5c-47d8-9068-8478b507fd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;z-WorkspaceHolder&quot;]/div[2]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[2]/div[@class=&quot;gwt-SplitLayoutPanel&quot;]/div[4]/div[@class=&quot;z-DataView z-DataView-Selected&quot;]/div[2]/div[1]/div[3]/div[@class=&quot;zrl-FlexVertical z-Workspace&quot;]/div[@class=&quot;z-DisclosurePanel z-DisclosurePanel-closed z-RoundedPanelFullWidth&quot;]/div[@class=&quot;header&quot;]/a[@class=&quot;headerAnchor&quot;]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-DisclosureIcon z-DisclosureIcon-down-hovering&quot;]/img[@class=&quot;z-DisclosureIcon-Image&quot;]</value>
      <webElementGuid>dfcf1059-fd93-43bd-9672-b0d27e6acfb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/img</value>
      <webElementGuid>951bdf14-49df-472a-b89b-e97786189b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'system/icons/disclosure_right.png']</value>
      <webElementGuid>94c15af5-30c7-4eb5-acb2-5d67e0cbfc97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
